# Generated by Django 5.0.4 on 2024-07-04 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='emial',
            new_name='email',
        ),
    ]
